version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout

      - run: |
        mkdir dist
        cp README.md dist
      - store_artifacts:
        path: /dist/README.md