version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - run: pwd && mkdir dist && cp README.md dist/README.md && ls dist
      - store_artifacts:
          path: /dist